Make stdlib's regex flag constants available here.
davidblewett/rure-python pull request #4
Opened 2016-11-16 16:25 UTC by mattdeboard

This lets users do like

```python
import rure as re
reo = re.Rure(b"\\p{So}$", flags=re.IGNORECASE)
```

2016-11-16 21:41 UTC, davidblewett requested changes

2016-11-16 21:41 UTC, davidblewett commented on rure/__init__.py
> +
These shortcuts aren't valid; the constant values are different. It's the reason for the `FLAG_MAP` here: https://github.com/davidblewett/rure-python/blob/master/rure/regex.py#L11 .

2016-11-16 21:41 UTC, davidblewett commented on rure/__init__.py
> +
I do like the ergonomics of re-exporting the stdlib constants though.

2016-11-16 22:11 UTC, mattdeboard commented on rure/__init__.py
> +
Yeah that's what I was going for was "ergonomics" (good word for it). You can close this if it's too far off the mark.

2016-11-17 16:57 UTC, davidblewett commented on rure/__init__.py
> +
I do think it's worthwhile, but just not setting them equal to the Rure constants. Let's just import the names from `re` and be done.

2016-11-24 22:45 UTC, mattdeboard commented
Updated per our convo.

2016-11-25 19:25 UTC, merged